# Generated by Django 3.1 on 2020-08-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='lugarNacimiento',
            new_name='lugarResidencia',
        ),
    ]
